Tram-One/tram-one

- package.json
- tests/specs/tram-spec.js
- tram-one.js
Make methods return an instance of the app, so that you can chain multiple methods. This logic is completely backwards compatible, as these methods were previously void.
Resolves #10 
Example:
```javascript
app = new Tram()
.addRoute('/', () => Tram.html()`<div>Home</div>`)
.addRoute('/404', () => Tram.html()`<div>Error</div>`)
.start('.main')
```
- `addReducer` returns an instance of `this`
- `addRoute` returns an instance of `this`
- `start` returns an instance of `this`
- `mount` returns an instance of `this`
> Make methods Chainable ⛓, Release 1.2.0

- README.md
- examples/using-reducers/index.js
- package.json
- tests/specs/tram-spec.js
- tests/testem.html
- tram-one.js
Resolves #3 
Start #8 
- update readme
- added url-listener package to handle push, pop, and hash events
- refactor tests to work with url-listener
- start should trigger the url-listener for popstates
- update jasmine version
> Use url-listener to handle push, pop, and hash events

- configs/testem.yml
Adds chrome headless to the browsers run by default by testem.
Keeping PhantomJS because it mimics IE support fairly closely.
> Chrome Headless!

- README.md
- package-lock.json
- package.json
This includes the changes to support self-closing tags (as documented in https://github.com/choojs/hyperx/pull/58)
Resolves #36 
* allow custom elements to be self-closing 
```javascript
const emptyTag = () => html`<span>my tag</span>`
const html = Tram.html({'empty-tag': emptyTag})
// before
html`<div><empty-tag></empty-tag>Hello</div>`
//  returns: <div><span>my tag</span>Hello</div>
// after
html`<div><empty-tag />Hello</div>`
// returns:  <div><span>my tag</span>Hello</div>
```
This may break current functionality depending on how you wrote tags that were already considered self-closing (e.g. `<br>`). Those tags **need** to now have an ending `/>` in their tag.
> add support for self-closing tags

- README.md
- package-lock.json
- package.json
In npmjs.org, the images for the build sizes did not render because they did not exist locally from that address. This fixes them to github, which kinda stinks, but should be easy to change should the project ever decide to move from github (which is extremely unlikely)
> use absolute links so that npm renders properly

- .circleci/config.yml
- configs/testem.yml
- package-lock.json
- package.json
Version 4.0.1 (#77) broke CircleCI tests because of the version of Firefox (47 vs the current version 58) has an unreproducible bug. 
For now we are skipping tests in the CircleCI environment on Firefox, until they update the version, or we build our own Docker Image.
- Firefox now runs in dev mode with `--headless` flag
- `--skip` flag is used for testem to avoid running in unsupported browsers
We are formally dropping support for these browsers for 2 reasons:
1. They are no longer the defacto browsers for their domain (Edge is the new default on windows machines, and headless chrome / headless firefox far out-perform PhantomJS)
2. Template Literals have no trivial transpile equivalent, and these browsers do not support template literals. As it stands, making sites for these browsers …
> Debugging CircleCI tests

- README.md
- docs/images/esm.svg
- tram-one.js
This should make the README easier to read and more consistent.
Preview: https://github.com/Tram-One/tram-one/blob/terminology/README.md#api
Resolves #88 
and resolves #47
> add terminology and links in README

- README.md
- configs/rollup.config.umd.js
- dev-scripts/badge.js
- docs/images/esm.svg
- docs/images/umd.svg
- examples/umd-example/index.html
- package-lock.json
- package.json
Make main export the ES module, that way asserts will be visible when doing initial development. 
- #85 
- https://github.com/Tram-One/tram-one-express/issues/22
- updated svg badges to be cleaner
- updated unpkg links to point to umd
> Make Default Export ES Module

- docs/images/esm.svg
- docs/images/umd.svg
- package-lock.json
- package.json
- tests/specs/tram-spec.js
- tram-one.js
Originally nested routes with redundant `/` would cause conflicts in resolving the route. Since `//` is never going to be valid, it's safe to reduce instances of these to `/`.
```javascript
app.addRoute('/', require('./pages/Chrome'), [
route('about', require('./pages/HomePage')),
route('images/:albumPage', require('./pages/ImageSetPage')),
route('404', require('./pages/404'))
])
```
```javascript
app.addRoute('/', require('./pages/Chrome'), [
route('/about', require('./pages/HomePage')),
route('/images/:albumPage', require('./pages/ImageSetPage')),
route('/404', require('./pages/404'))
])
```
- bump eslint version
> Handle redundant slashes in routes

- README.md
- docs/images/esm.svg
- docs/images/umd.svg
- examples/using-listeners/index.js
- package-lock.json
- package.json
- tests/specs/tram-spec.js
- tram-one.js
Add hover-battery, to tram-one project. This will allow projects by default to keep session between page reloads.
By default we'll save to `sessionStorage`. However we'll add this as a variable that can be set when calling the constructor.
```javascript
const app = new Tram({webStorage: localStroage})
```
- add `hover-battery` to project
- new option in constructor, `webStorage`, defaults to `sessionStorage`
- tests around `webStorage` option, as the default and with a mockStorage object
- Removed references to using `addListener` to save to localStorage
- Bump minor: version 5.2.0
> Add Hover-Battery

- docs/images/esm.svg
- docs/images/umd.svg
- package-lock.json
- package.json
- tests/specs/tram-spec.js
- tram-one.js
After working with `sessionStorage` as the default `webStorage`, it became painfully obvious that `sessionStorage` as the default is a bad idea. It makes debugging and playing around with different state options incredibly difficult.
Making the default should effectively make development the same as not having hover-battery at all, and it's still easy to enable webStorage with the constructor option.
Potentially, we could remove the package altogether, but I like the idea of having this quickly available (like state management, you might not need it, but it's there for you).
We are bumping major because we have made a change to the defaults, which may be unexpected to users with unchanged configurations.
> Make Default WebStorage undefined

- docs/images/umd.svg
- package-lock.json
- package.json
Update to include changes in https://github.com/Tram-One/hover-battery/pull/2
> SafeParse with new version of Hover-Battery

- examples/ssr-example/README.md
- examples/ssr-example/index.js
- examples/ssr-example/main.js
- examples/ssr-example/server.js
- examples/ssr-example/webpack.config.js
Previously, for our Server Side Rendering (SSR) example, we could only render the page without javascript. The example has been updated to include a script tag pointing to a webpack build, which should "hydrate" the app with javascript on page load.
Resolves #35
> Server Side Rendering & Hydration Example

- docs/images/esm.svg
- docs/images/umd.svg
- package-lock.json
- package.json
- tests/specs/tram-spec.js
- tests/testem.html
- tram-one.js
In the past, it was non trivial to have a default child for a route when using subroutes. This is because if you defined a child at `/` and a parent at `/`, the child would be assigned in the router first, and then replaced by the parent definition.
```javascript
app.addRoute('/', require('./pages/wrapper'), [ // assigned second
route('/', require('./pages/home')), // assigned first, replaced by /pages/wrapper
route('/404', require('./pages/404')),
route('/privacy', require('./pages/privacy')),
route('/opensource', require('./pages/opensource')),
])
app.toString('/')  // => renders /pages/wrapper
```
This PR allows the above to be written and processed in the correct order.
```javascript
app.addRoute('/', require('./pages/wrapper'), [ // not assigned
route('/', require('./pages/home')), …
```
> Allow Default Subroutes

- configs/webpack.config.testem.js
- dev-scripts/example-selector.js
- docs/images/esm.svg
- docs/images/umd.svg
- examples/using-actions/index.js
- examples/using-custom-elements/index.js
- package-lock.json
- package.json
- tests/specs/tram-spec.js
- tram-one.js
If you don't `start` the app, then webEngine remains empty, even if `addAction` calls have been made. This means any attempt to call actions or look at store props before the app has started will fail.
```javascript
const app = new Tram({ webEngine: {} })
app.addActions( ... )
console.log(app.webEngine) // -> undefined
```
This PR (among other things) checks if webEngine exists and updates the store and actions on `addActions`. A test has been added to validate this functionality.
I realized that some old example launchers were still in the repo, so those have been removed. The `xo` dependency has been pinned (since it still remains in pre-release, so `^` was pulling breaking changes). The examples that do exist have been updated to reference the forked dependencies.
> Fix: populate webEngine on addAction

- docs/badges/cjs.svg
- docs/badges/umd.svg
- package.json
- src/engine-names/index.js
- src/mount/mount.js
- src/mount/mount.test.js
- src/render-tracker/index.js
- src/render-tracker/render-tracker.js
- src/render-tracker/render-tracker.test.js
- src/start/start.js
- src/tram-one/tram-one.test.js
Missing commits from #114 , includes a new render-tracker which will prevent re-renders that show old dom, and psuedo integration tests.
> render-tracker and tram-one tests

- docs/badges/umd.svg
- integration-tests/specs/updated-effect-spec/updated-effect-spec.js
- package-lock.json
- package.json
- src/mount/mount.js
Effect store was not clearing if there was no cleanup, this change ensures that even if there is no cleanup that we remove the effect from the store. 
* added new integration tests
> fix effect store bug, bump patch v8.1.1

- configs/docma.json
This PR updates the sandbox link to use the linked template that we now generate (https://github.com/Tram-One/tram-one-express/pull/88). You can see this link now on the website under the *Try Now* dropdown.
> update sandbox link to reflect tram-one-express template

- configs/docma.json
This PR removes removes the link at the top of the page for hacktoberfest. The page still exists, so that we don't 404, and can re-use it for Hacktoberfest next year.
> remove hacktoberfest link

- configs/docma.json
- docs/badges/cjs.svg
- docs/guides/introduction.md
- package-lock.json
- package.json
- src/dom-wrappers.js
- src/start.js
- src/use-effect.js
- src/use-global-observable.js
- src/use-observable.js
- src/use-url-params.js
Realized that Stackblitz (which we were trying out in the previous PR), hasn't been updated in a long while, and offers less options when compared to CodeSandbox. So we've created a new repository for the samples (https://github.com/Tram-One/tram-one-samples), and we link directly to those on the website.
> update website to use codesandbox samples

- docs/badges/cjs.svg
- docs/badges/umd.svg
- integration-tests/regression.test.js
- integration-tests/test-app/index.js
- integration-tests/test-app/tasks.js
- package-lock.json
- package.json
- src/observable-hook.js
- src/use-global-store.js
- src/use-store.js
In the release of v10, the ability to store arrays was broken (because to make a shallow copy, the spread syntax for objects was used, but this inadvertently changed arrays to objects). There was no regression test for this, so a new one has been added.
> Fix Array in useStore (v10.0.1)

- docs/badges/cjs.svg
- docs/badges/umd.svg
- integration-tests/integration.test.js
- integration-tests/regression.test.js
- integration-tests/test-app/account.js
- package-lock.json
- package.json
- src/use-url-params.js
There is a bug in the existing version of Tram-One, where on initial load, the url parameters live in a `params` field. This is only true for the first render, and then afterwards works as expected (with keys at the top level). 
This PR fixes the issue, and adds a regression test to verify the behavior acts as expected.
> Fix Initial useUrlParams bug

- docs/badges/cjs.svg
- docs/badges/umd.svg
- integration-tests/regression.test.js
- integration-tests/test-app/tasks.js
- package-lock.json
- package.json
- src/start-focus-tracker.js
Previously, when interacting with multiple inputs, focus would be thrown onto the wrong element when the component refreshed. This PR removes the focus marker when the `focusout` event occurs.
> Remove focus marker on elements

- package.json
Update the `package.json` to include the runkit example in the npm package. 
I believe including this document in the npm package will allow RunKit to pick up the file (whereas it currently can not find the file).
> Include runkit example in npm distributable

- docs/badges/cjs.svg
- docs/badges/umd.svg
- integration-tests/regression.test.js
- integration-tests/test-app/sub-mirror-input.js
- package-lock.json
- package.json
- src/observe-tag.js
Fixes an issue where if the elements were re-ordered or changed significantly, we wouldn't be able to re-attach focus. Worse so, we never check if the element exists before trying to focus it, so we would get an error!
This PR also fixes an error where the scroll position would be reset when typing in an input. 
When interacting with an input that has `<span>-</span>` for every letter in the input. This is what happens when typing and then deleting (this is the integration test app, which can be run locally with `npm run test:app`):
The first set of errors is because we are trying to `setSelectionRange` on a `<span>`, the second error is because after deleting no element exists at the index that the `<input>` was on.
No errors :tada:
> Fix input focus on re-ordered elements

- package-lock.json
- package.json
- performance-tests/__snapshots__/performance.test.js.snap
- performance-tests/performance.test.js
- performance-tests/test-app/element-rendering.js
- performance-tests/test-app/index.html
- performance-tests/test-app/index.js
Fixes #39 
This PR is an attempt to set up a framework for us to add tests that verify the performance of tram-one. All of the infrastructure is identical to the existing unit tests, but has uses performance timers and helper functions to get metrics of how slow tram-one was to update. It currently uses snapshots as artifacts of the timers.
> initial work for adding performance tests

- package-lock.json
- package.json
- performance-tests/__snapshots__/performance.test.js.snap
- performance-tests/test-app/element-rendering.js
- src/dom.js
- src/mutation-observer.js
- src/node-names.js
- src/observe-tag.js
* Removes `querySelectorAll` and uses TreeWalkers instead
* names previously anonymous functions so that they appear in the performance debugger
* Fix an issue with reseting scroll position on elements that have none
Changes to improve the performance throughout the framework. See the PR comments for more details!
> initial set of performance improvements

- .circleci/config.yml
- docs/badges/cjs.svg
- package-lock.json
- package.json
- performance-tests/__snapshots__/performance.test.js.snap
- performance-tests/performance.test.js
- src/tram-one.js
This PR adds the configuration to run the performance tests on CircleCI, makes them a little more consistent, and pushes the performance tests (and build badges!) back to the repo.
* When working on a non-master branch, this creates a new branch with the `-artifacts` suffix.
* These branches never have to be merged (we will have to clean them up later, but that's fine for now)
* When working on master (after a PR has been merged), this creates a new commit straight on master
* This will include the final performance result and badge result, regardless of whatever was committed in the PR
Performance Results - https://github.com/Tram-One/tram-one/compare/performance-test-on-ci...performance-test-on-ci-artifacts
* This followed the following guide to setup the pushing from CircleCI - …
> Test Performance on CI

- README.md
- package-lock.json
- package.json
While building the org badges, I realized that we had pointed to the umd one twice. Additionally, decided to use a discord color for the discord one.
[You can see what the final result looks like here](https://github.com/Tram-One/tram-one/blob/update-badge-icons/README.md)
> Update Badge Icons

- integration-tests/test-app/sub-title.ts
- integration-tests/test-app/title.ts
- package-lock.json
- package.json
- src/dom.ts
- src/mount.ts
- src/start.ts
- src/types.ts
Update Tram-One types to use generics for component definitions! 
This mimics React's component prop type definitions.
This is a patch because it fixes a previously broken workflow. While this technically could introduce typescript errors where there weren't any before, those should be considered broken.
```ts
type pageHeaderProps = {
index: number;
};
const pageHeader: TramOneComponent<pageHeaderProps> = ({ index }) => {
const targetGroupPage = useTargetGroupPage(index);
return html`
<h1 class="page-header">
<span>${targetGroupPage.title || ""}</span>
</h1>
`;
```
> Type Updates - Tram One Generics

- integration-tests/integration.test.js
- integration-tests/regression.test.js
- integration-tests/test-app/anchor-set.ts
- integration-tests/test-app/anchors.ts
- integration-tests/test-app/focus-input.ts
- integration-tests/test-app/index.ts
- integration-tests/test-app/tram-input.ts
- package-lock.json
- package.json
- src/dom-wrappers.ts
- src/dom.ts
- src/mount.ts
- src/mutation-observer.ts
- src/process-hooks.ts
- src/types.ts
- src/use-url-params.ts
This PR makes updates to how `useEffect` works, mostly in prep for #173 
Fixes #130 
Fixes #166
Fixes #112 
* process existing effects 
* these were prepared a while ago (in #142), but we finally found a way to test them in #166
* add `ref` parameter to `useEffect`.
* this has been discussed for a while in #130, this solution feels the most directly applicable, in the example applications built so far.  
* changed top level element to be `<tram-one>` rather than `<div>`, this is more clear and obvious, and won't cause formatting issues (since `<tram-one>` should be undecorated). 
* #112
* make the pattern parameter for `useUrlParams` optional (the underlying library has a default value here, so no parameter should be required).
* Some underlying types were more explicitly defined
* This …
> Existing Effects & Refs
